schema_version = "1.0.0"

id = "osc_recorder"
version = "1.0.0"
name = "OSC Recorder"
tagline = "Receive OSC data and record it to animation keyframes"
type = "add-on"

blender_version_min = "4.0.0"

maintainer  = "Carlos Carbonell"
license = ["SPDX:CC0-1.0"]
permissions = ["network"]
categories = ["System"]
modules = ["main"]